server:
  port: 9191

spring:
  application :
    name : API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri : lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name : CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri : forward:/orderServiceFallback
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
              - Path=/carts/**
          filters:
            - name: CircuitBreaker
              args:
                name: CART-SERVICE
                fallbackuri: forward:/cartServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost